# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  BINARY: rmm-tracker
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  GIT_COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  BUILD_TIME:
    sh: date -u +%Y-%m-%dT%H:%M:%SZ
  DATABASE_URL: postgres://rmm:rmm@localhost:5432/rmm_tracker?sslmode=disable
  COVERAGE_FILE: coverage.out
  DOCKER_HUB_USER: matrixise
  DOCKER_HUB_IMAGE: "{{.DOCKER_HUB_USER}}/rmm-tracker"

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list
    silent: true

  # ── Build ──────────────────────────────────────────────

  build:
    desc: Build the binary
    cmds:
      - go build -ldflags "-X github.com/matrixise/rmm-tracker/cmd.Version={{.VERSION}} -X github.com/matrixise/rmm-tracker/cmd.GitCommit={{.GIT_COMMIT}} -X github.com/matrixise/rmm-tracker/cmd.BuildTime={{.BUILD_TIME}}" -o {{.BINARY}} .
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BINARY}}"

  # ── Test ───────────────────────────────────────────────

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  test:verbose:
    desc: Run all tests with verbose output
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - go test ./... -coverprofile={{.COVERAGE_FILE}}
      - go tool cover -func={{.COVERAGE_FILE}}

  test:coverage:html:
    desc: Run tests and open coverage in browser
    deps: [test:coverage]
    cmds:
      - go tool cover -html={{.COVERAGE_FILE}}

  # ── Database ───────────────────────────────────────────

  migrate:up:
    desc: Apply all pending migrations
    cmds:
      - DATABASE_URL={{.DATABASE_URL}} go run . migrate up

  migrate:down:
    desc: Rollback the last migration
    cmds:
      - DATABASE_URL={{.DATABASE_URL}} go run . migrate down

  migrate:status:
    desc: Show migration status
    cmds:
      - DATABASE_URL={{.DATABASE_URL}} go run . migrate status

  # ── Docker ─────────────────────────────────────────────

  docker:build:
    desc: Build the Docker image
    cmds:
      - docker compose build --build-arg VERSION={{.VERSION}} --build-arg GIT_COMMIT={{.GIT_COMMIT}} --build-arg BUILD_TIME={{.BUILD_TIME}}

  docker:up:
    desc: Start all services (PostgreSQL + app)
    cmds:
      - docker compose up -d

  docker:down:
    desc: Stop all services
    cmds:
      - docker compose down

  docker:logs:
    desc: Follow application logs
    cmds:
      - docker compose logs -f app

  docker:ps:
    desc: Show running containers and health status
    cmds:
      - docker compose ps

  docker:buildx:setup:
    desc: Setup Docker buildx for multi-arch builds
    cmds:
      - docker buildx create --name rmm-builder --use --bootstrap || docker buildx use rmm-builder
      - docker buildx inspect --bootstrap
    status:
      - docker buildx ls | grep rmm-builder

  docker:buildx:build:
    desc: Build linux/amd64 image and load into Docker (for deployment testing)
    deps: [docker:buildx:setup]
    cmds:
      - |
        docker buildx build \
          --builder rmm-builder \
          --platform linux/amd64 \
          --build-arg VERSION={{.VERSION}} \
          --build-arg GIT_COMMIT={{.GIT_COMMIT}} \
          --build-arg BUILD_TIME={{.BUILD_TIME}} \
          --cache-to type=inline \
          -t {{.DOCKER_HUB_IMAGE}}:{{.VERSION}} \
          -t {{.DOCKER_HUB_IMAGE}}:latest \
          --load \
          .

  docker:buildx:push:
    desc: Build and push multi-arch image (AMD64 + ARM64) to Docker Hub
    deps: [docker:buildx:setup]
    cmds:
      - |
        docker buildx build \
          --builder rmm-builder \
          --platform linux/amd64,linux/arm64 \
          --build-arg VERSION={{.VERSION}} \
          --build-arg GIT_COMMIT={{.GIT_COMMIT}} \
          --build-arg BUILD_TIME={{.BUILD_TIME}} \
          --cache-from type=registry,ref={{.DOCKER_HUB_IMAGE}}:buildcache \
          --cache-to type=registry,ref={{.DOCKER_HUB_IMAGE}}:buildcache,mode=max \
          -t {{.DOCKER_HUB_IMAGE}}:{{.VERSION}} \
          -t {{.DOCKER_HUB_IMAGE}}:latest \
          --push \
          .

  docker:cache:clear:
    desc: Clear Docker build cache
    cmds:
      - docker buildx prune --builder rmm-builder -f

  # ── Development ────────────────────────────────────────

  run:
    desc: Run the tracker once (requires DATABASE_URL)
    deps: [build]
    cmds:
      - DATABASE_URL={{.DATABASE_URL}} ./{{.BINARY}} run --once

  run:daemon:
    desc: Run in daemon mode (5m interval)
    deps: [build]
    cmds:
      - DATABASE_URL={{.DATABASE_URL}} ./{{.BINARY}} run --interval 5m

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.BINARY}} {{.COVERAGE_FILE}}

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...
