# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  BINARY: rmm-tracker
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  GIT_COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  BUILD_TIME:
    sh: date -u +%Y-%m-%dT%H:%M:%SZ
  DATABASE_URL: postgres://realt:realt@localhost:5432/realt_rmm?sslmode=disable
  COVERAGE_FILE: coverage.out

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list
    silent: true

  # ── Build ──────────────────────────────────────────────

  build:
    desc: Build the binary
    cmds:
      - go build -ldflags "-X github.com/matrixise/rmm-tracker/cmd.Version={{.VERSION}} -X github.com/matrixise/rmm-tracker/cmd.GitCommit={{.GIT_COMMIT}} -X github.com/matrixise/rmm-tracker/cmd.BuildTime={{.BUILD_TIME}}" -o {{.BINARY}} .
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BINARY}}"

  # ── Test ───────────────────────────────────────────────

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  test:verbose:
    desc: Run all tests with verbose output
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - go test ./... -coverprofile={{.COVERAGE_FILE}}
      - go tool cover -func={{.COVERAGE_FILE}}

  test:coverage:html:
    desc: Run tests and open coverage in browser
    deps: [test:coverage]
    cmds:
      - go tool cover -html={{.COVERAGE_FILE}}

  # ── Database ───────────────────────────────────────────

  migrate:up:
    desc: Apply all pending migrations
    cmds:
      - DATABASE_URL={{.DATABASE_URL}} go run . migrate up

  migrate:down:
    desc: Rollback the last migration
    cmds:
      - DATABASE_URL={{.DATABASE_URL}} go run . migrate down

  migrate:status:
    desc: Show migration status
    cmds:
      - DATABASE_URL={{.DATABASE_URL}} go run . migrate status

  # ── Docker ─────────────────────────────────────────────

  docker:build:
    desc: Build the Docker image
    cmds:
      - docker compose build --build-arg VERSION={{.VERSION}} --build-arg GIT_COMMIT={{.GIT_COMMIT}} --build-arg BUILD_TIME={{.BUILD_TIME}}

  docker:up:
    desc: Start all services (PostgreSQL + app)
    cmds:
      - docker compose up -d

  docker:down:
    desc: Stop all services
    cmds:
      - docker compose down

  docker:logs:
    desc: Follow application logs
    cmds:
      - docker compose logs -f app

  docker:ps:
    desc: Show running containers and health status
    cmds:
      - docker compose ps

  # ── Development ────────────────────────────────────────

  run:
    desc: Run the tracker once (requires DATABASE_URL)
    deps: [build]
    cmds:
      - DATABASE_URL={{.DATABASE_URL}} ./{{.BINARY}} run --once

  run:daemon:
    desc: Run in daemon mode (5m interval)
    deps: [build]
    cmds:
      - DATABASE_URL={{.DATABASE_URL}} ./{{.BINARY}} run --interval 5m

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.BINARY}} {{.COVERAGE_FILE}}

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...
