// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Changelog(html string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style type=\"text/tailwindcss\">\n\t\t\t.md h1 { @apply text-3xl font-bold text-gray-900 mt-8 mb-4; }\n\t\t\t.md h2 { @apply text-2xl font-semibold text-gray-800 mt-8 mb-3 pb-2 border-b border-gray-200; }\n\t\t\t.md h3 { @apply text-lg font-semibold text-gray-800 mt-6 mb-2; }\n\t\t\t.md p  { @apply text-gray-700 leading-relaxed mb-4; }\n\t\t\t.md ul { @apply list-disc list-inside space-y-1 mb-4 text-gray-700 pl-4; }\n\t\t\t.md ol { @apply list-decimal list-inside space-y-1 mb-4 text-gray-700 pl-4; }\n\t\t\t.md li { @apply leading-relaxed; }\n\t\t\t.md a  { @apply text-indigo-600 hover:text-indigo-800 hover:underline; }\n\t\t\t.md code { @apply bg-gray-100 text-sm font-mono px-1.5 py-0.5 rounded; }\n\t\t\t.md pre { @apply bg-gray-100 rounded-lg p-4 mb-4 overflow-x-auto text-sm font-mono; }\n\t\t\t.md pre code { @apply bg-transparent p-0; }\n\t\t\t.md strong { @apply font-semibold; }\n\t\t\t.md blockquote { @apply border-l-4 border-gray-300 pl-4 italic text-gray-600 mb-4; }\n\t\t\t.md hr { @apply border-gray-200 my-6; }\n\t\t</style> <div class=\"bg-white shadow rounded-lg p-8\"><div class=\"md\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.Raw(html).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Layout("Changelog").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
